// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2025-2026 Dendri contributors

use std::collections::HashSet;
use std::time::Duration;

use tokio::sync::watch;

use crate::models::message::Message;
use crate::redis_realm;
use crate::state::AppState;

/// Background task that expires queued messages after expire_timeout.
/// Sends deduplicated EXPIRE messages back to the original senders.
pub async fn run(state: AppState, mut shutdown: watch::Receiver<bool>) {
    let interval = Duration::from_millis(state.config.cleanup_out_msgs);
    let expire_timeout_ms = state.config.expire_timeout as i64;

    loop {
        tokio::select! {
            _ = tokio::time::sleep(interval) => {}
            _ = shutdown.changed() => {
                tracing::info!("messages_expire shutting down");
                return;
            }
        }

        let queue_ids = match redis_realm::get_client_ids_with_queue(&state.redis).await {
            Ok(ids) => ids,
            Err(e) => {
                tracing::error!("Redis error in messages_expire: {e}");
                continue;
            }
        };

        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_millis() as i64;

        for dst_id in queue_ids {
            let last_read_at = redis_realm::get_queue_last_read_at(&state.redis, &dst_id)
                .await
                .unwrap_or(None)
                .unwrap_or(0);

            if now - last_read_at < expire_timeout_ms {
                continue;
            }

            let messages = redis_realm::read_all_messages(&state.redis, &dst_id)
                .await
                .unwrap_or_default();

            let mut seen = HashSet::new();

            for msg_json in &messages {
                let Ok(msg) = serde_json::from_str::<Message>(msg_json) else {
                    continue;
                };

                let src = msg.src.as_deref().unwrap_or("");
                let dst = msg.dst.as_deref().unwrap_or("");
                let seen_key = format!("{src}_{dst}");

                if seen.contains(&seen_key) {
                    continue;
                }
                seen.insert(seen_key);

                let data = format!(r#"{{"type":"EXPIRE","src":"{}","dst":"{}"}}"#, dst, src);

                if let Some(sender) = state.ws_senders.get(src) {
                    let _ = sender.send(data);
                }
            }

            let _ = redis_realm::clear_message_queue(&state.redis, &dst_id).await;
        }
    }
}

#[cfg(test)]
mod tests {
    use std::collections::HashSet;

    /// Regression test: verify that expired messages generate EXPIRE
    /// notifications for each unique sender-destination pair.
    /// Tests the deduplication logic (same src-dst pair should only
    /// generate one EXPIRE) and the JSON format of the generated message.
    #[test]
    fn expire_message_handles_dedup_and_format() {
        // Simulate the JSON generated by messages_expire for a given (src, dst).
        let src = "peer-a";
        let dst = "peer-b";
        let data = format!(r#"{{"type":"EXPIRE","src":"{}","dst":"{}"}}"#, dst, src);

        let parsed: serde_json::Value = serde_json::from_str(&data).unwrap();
        assert_eq!(parsed["type"], "EXPIRE");
        assert_eq!(parsed["src"], dst);
        assert_eq!(parsed["dst"], src);
    }

    /// Verify that the Seen HashSet correctly deduplicates src-dst pairs.
    /// Multiple messages from the same src to the same dst should produce
    /// only one EXPIRE notification.
    #[test]
    fn expire_dedup_avoids_duplicate_expire() {
        let mut seen: HashSet<String> = HashSet::new();
        let messages = vec![
            ("alice", "bob"),
            ("alice", "bob"), // duplicate
            ("carol", "bob"),
            ("alice", "dave"),
        ];

        let mut expire_count = 0;
        for (src, dst) in &messages {
            let key = format!("{}_{}", src, dst);
            if seen.contains(&key) {
                continue;
            }
            seen.insert(key);
            expire_count += 1;
        }

        // 3 unique pairs out of 4 messages.
        assert_eq!(expire_count, 3);
        assert_eq!(seen.len(), 3);
    }
}
